### PR TITLE
added meta tag for nulls Last sorting

### PR DESCRIPTION
**Pull request by StefanMitt**

### CODE REVIEW

**Comment by StefanMitt** [comment]
https://github.com/laravel-enso/Documentation/pull/6

**Comment by aocneanu** [comment]
one more thing beside what I wrote in the review, let's use for the param `nullLast` instead of `nullsLast`.

**Comment by aocneanu** [comment]
@StefanMitt did you notice the PR review?

**Comment by aocneanu** [comment]
once those are done I'm ready to merge

**Comment by StefanMitt** [comment]
> @StefanMitt did you notice the PR review?
unfortunately i don't see any PR reviews on this PR.

**Comment by aocneanu** [comment]
@StefanMitt can you see the review now?

**Comment by StefanMitt** [comment]
Yes i can see it now, will resolve it later today or tomorrow.

**Pull request merged**
