### PR TITLE
Select all button added to topControls & isSelected action helper

### PR DESCRIPTION
**Pull request by clnt**
This is  a **feature**.

### Prerequisites
* [✅] Are you running the latest version?
* [✅] Are you reporting to the correct repository?
* [✅] Did you check the documentation?
* [✅] Did you perform a cursory search?

### Description
Hey!

This PR adds a select all button to the topControls and an `isSelected()` helper function to the Action class. 

The helper function was the best method I could think of for checking if selected in actions, I tried modifying the action to only loop through the selected data, however this seemed to have some adverse affects on performance (not so noticable for smaller data sets, but I was testing with 200k).

The select all button required me to make some modifications to the Builder, I needed to capture the filtered data before the `limit()` function is run, this also has some affects on performance when testing with 200k records, so for this reason I have gated the select all option behind `fullRecordInfo`, if this is not true the button will not show, and the `raw` property will not get populated.

You will notice I have removed the `selected` prop from TableBody and updated the select functions to directly modify the `$parent.selected`. The reason I have done this is I was getting some unexpected results when hooking into the `update-selected` event within my application, i.e. I could select the first row in the table but the emitted array is empty. With this change everything is working great!

The final thing I have done is add `selected` to the export request data.

(hopefully the spacing/new lines are all correct in this!)

### CODE REVIEW

**Comment by aocneanu** [comment]
Cool, I will have time to look in depth early next week.

Thank you.

**Comment by clnt** [comment]
No problem :)

I've just pushed a commit which adds a `select` prop, this allows for an array of ID's to be passed so that existing data can be selected.

**Comment by aocneanu** [comment]
Hi @clnt,

I just looked at the implementation and I want first to understand the desired behaviour. Please describe in detail how you are seeing this functionality working.

From what I saw you added a `raw` property from the SS that is return to the front end. Is this going to hold/return all the (let's say f.e. 100k) records from the database?

**Comment by clnt** [comment]
Hey,

Yeah essentially the `raw` property is the raw query data without being narrowed down for pagination. This was the best method I could think of at the time, this is why I wanted to gate the select all function behind the `fullRecordInfo` limit as when testing with 200k records the performance was not optimal.

Not sure if you can see a better way of handling it? 

How I see it is, it can either fetch all of the ID's in table on `getData()` and populate the `raw`, downside with this is it has to generate it again for every search.

Or, remove the `raw` property and have the select all button perform an axios request to fetch an array of all ID's to select, thinking about it this would probably be the best option for performance.

**Comment by aocneanu** [comment]
Fetching all data or all ids is not something that we want. We have applications with tables that return millions of rows and we don't want to get that amount of data in the front-end.

I suggest we keep the discussion open until we know exactly what are the use cases for this functionality and then choose the best implementation.

For example, we can send to the server's `Action` class a `selectAll` flag and it could be enough. For the front-end, as long as we have the selectAll checked we could display all the lines selected with a readonly checkbox, and don't allow to the user to unselect rows individually. This would cover some use scenarios.

**Comment by clnt** [comment]
I agree, looking back this isn't the right way to approach it! When I have some more time I will see if I can come up with a better implementation, without delivering all of the data to the frontend :)

**Comment by aocneanu** [comment]
I think that first we should find out exactly what we want and what are the use cases. After we will start thinking of the best implementation.

**Comment by clnt** [comment]
Okay, no problem sounds good!

The main reason for the select feature for me, is dealing with adding members to a group. The names of these members in my system follow a naming convention, so the user can easily search the start of the name, this is where the select all option would come in handy as most of the time a group will consist of members with the same prefix and there could be several pages.

Your idea of a `selectAll` flag being sent with the request could work for my use case, if it is set then all checkboxes should be selected. The only limitation I can see with this implementation is being able to select all records, but unable to deselect certain records. Unless when `selectAll` is `true` we could generate a `deselected` array to send with the request which can be filtered out in the backend.

**Comment by aocneanu** [comment]
we will close this for now, and reopen it when the time comes.

**Pull request closed without merging**
