### PR TITLE
Ajax POST support and add keys to request when params specified

### PR DESCRIPTION
**Pull request by clnt**
I hit some issues sending Ajax post requests from buttons in the table row, even when using POST it was forming the request like this: `/admin/customer/delete?7`

Also, when sending a GET/DELETE request I needed the URI formed like `/admin/customer/delete?id=7`

I have made a few of changes, which I believe should not break anything!:

- Modified the way `$button->path` is formed, it will now check if `params` has been defined for the row button in the template, if it has it will use them in forming the route. This is great when defining a route like `Route::get('/delete/{id}')->name('route.name');` as it will place `dtRowId` wherever `{id}` has been defined. Otherwise it will form it like `/admin/customers/delete?id=dtRowId`. If no `params` object has been defined it will form it like it does currently `/admin/customers/delete?dtRowId`.

- Altered the ajax event to also emit the route parameters, these will only be used if using the `POST` method.

- `ajax` method now checks if the method is a `POST` and will pass two arguments to the axios function, stripping parameters from the request URI.

Let me know what you think :)

### CODE REVIEW

**Comment by aocneanu** [comment]
I will look at this over the weekend

**Comment by aocneanu** [comment]
hey @clnt,

I started looking over this. I'm not sure that I understand where the problem lies, so help me break it down in individual problems.

>I hit some issues sending Ajax post requests from buttons in the table row, even when using POST it was forming the request like this: /admin/customer/delete?7

I wanted to replicate this so I changed:

- the destroy button's `method` from `DELETE` to `POST` in the [config](https://github.com/laravel-enso/Enso/blob/master/config/enso/datatable.php#L107).

- the [destroy route](https://github.com/laravel-enso/Enso/blob/master/routes/api.php#L53) by overwriting it with `Route::post('destroy/{id}', function () {return 'ok';})->name('destroy');`

The new route is:

image


And then when I press the delete button in the owners table:

image

image

Help me understand what's wrong.

Ah, please use the issue template from now on. And make sure that you describe one subject per issue. I feel that the current issue is a sort of bug report - question - feature request.

**Comment by clnt** [comment]
@aocneanu Hi mate, you are right it does work, I think there were some issues in the code I was testing with on friday, but these changes mostly came from some concerns with how it was handling the requests.

When I do a POST request, I don't expect to see the data I am posting in the request URI, it should be in the body of the request. 

I also made the modifications to the button path so that if params were defined like this:

```
params {
    "id": "dtRowId",
    "active": 1
}
```

It would also add the `active=1` onto the request if for example using a `GET` request.

I can work with it how it is, I just thought this would be a good QoL improvement :)

**Comment by aocneanu** [comment]
>When I do a POST request, I don't expect to see the data I am posting in the request URI, it should be in the body of the request.

It really not clear to me what you're trying to attend. Could you please describe the use case more clearly? Maybe share the template at least?

The objective of this package is to help the dev to easily implement a full featured CRUD. If one need something trickier, an edge case, there is always the option to use events.

**Comment by clnt** [comment]
@aocneanu I think I will close this PR, essentially the global buttons do this already by utilising the `action` method and using the `readRequest` method. When using row buttons in the table, these will typically only be edit/delete which most of the time will only require the ID passing.

I've got a better PR to open regarding the ability to select rows which I believe has been requested before, just got it working well, I shall use the issue template for this one ;)

**Pull request closed without merging**
