### PR TITLE
Adds params to button config.

### PR DESCRIPTION
**Pull request by mauthi**
#9

### CODE REVIEW

**Comment by aocneanu** [comment]
@gandesc What do you think?

At a first glance, it seems to me that for an edge case we would hardcode things on BE when we could do the same on FE and have the code even more readable for the custom scenario.

Share you opinion.

**Comment by mauthi** [comment]
@aocneanu I already discarded the part with changing the name of id param - but I still think that adding a params object to BE button json (see my commit) would be a good idea and in my opinion its no edge case?

**Comment by aocneanu** [comment]
@mauthi please give me a concrete example, to understand why would be preferable to hardcode an object in the BE instead of having control over it in the FE.

I'm not against the general idea, I just want to be sure that we develop something that would improve some scenarios against how we would implement the same scenarios with what we have now.

**Comment by mauthi** [comment]
I unterstand your view, its possible to define it on FE as well but I give you my concrete scenario where I would like to use this (and where its better to use it BE from my point of view):
- I have a customers page (table) and a invoice page (table)
- At customers table I have a button to view all invoices of one customer
- At invoices page I have a table and different filters at top (customer, project, ...) - the filters cards are closed by default
- If I click on "show invoices" button of one customer I jump to invoices page and would like to open customer filter
- therefore I use the following in button config
`params: { filterType: "customer" }`
- On invoice page I use the following to decide if filter is open
`this.$route.params.filterType`

**Comment by aocneanu** [comment]
Ok, so from what I understand you can also navigate to the invoice page directly, without going through customers, right?

**Comment by mauthi** [comment]
yes, you are right

**Comment by aocneanu** [comment]
Ok, so leaving aside the extra filter, when navigating from customers to invoices, you have in the invoices view a `customer_id` param, and when navigating directly, there's no `customer_id`, right?

**Comment by mauthi** [comment]
at the moment I'm using the `id` param of router for setting the customer id filter in table (did you mean this with your question?)

**Comment by mauthi** [comment]
> This means that with the current logic that you already wrote, you just have to query the this.$route.params.id to know if you need the filter open or not, instead of querying this.$route.params.filterType.

No thats not right because I have both project and customer filter on this page - so if the id is a customer id I would like to open customer filter, if id is a project id I would like to open project filter

> It seems that in this example you have a specific need given by the business logic that you implement, and maybe covering it should not be the responsibility of the vuetable component.

In this case you are right but I called the object "params" and its empty by default its just an additional possibility to make thinks customizable in json and does not change something on business logic itself?

**Comment by aocneanu** [comment]
Yes, I guess you're right, at the end it's only a feature that can be usefull. I will look at the code again.

**Comment by aocneanu** [comment]
Please remove `this` from the record info template and let's merge this PR and close the other that you opened.

**Comment by mauthi** [comment]
done

**Comment by mauthi** [comment]
I noticed that you tagged a new version but by running composer update I don't get this version - how is this linked to the main enso project?

**Comment by aocneanu** [comment]
There is a problem with the package auto update on this repo. I just refreshed it manually. In 2-3 minutes it will work.

Adrian Ocneanu
0722 44 33 77

**Comment by mauthi** [comment]
I think its the same with vuecomponents

**Comment by aocneanu** [comment]
https://packagist.org/packages/laravel-enso/vuecomponents <https://packagist.org/packages/laravel-enso/vuecomponents>

It's at 2.0.29, which is the last one.

Adrian Ocneanu
0722 44 33 77

**Comment by mauthi** [comment]
vudatatable updated worked now, thx.

**Pull request merged**
